version: '2'
services:
  web:
    command: "-u ghu"
    build:
      context: _/odoo
      args:
        ODOO_RELEASE: "20190508"
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./enterprise/addons:/mnt/enterprise-addons
      - ./enterprise/themes:/mnt/enterprise-themes
      - odoo-web-data:/var/lib/odoo
    networks:
      - db
      - smtp
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - db
  mailhog:
    image: mailhog/mailhog
    ports: 
      - 1026:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - smtp
volumes:
  odoo-web-data:
  odoo-db-data:
networks:
  smtp:
  db: